'use strict';

// ── Solidity code generator ───────────────────────────────────────────────────
//
// Takes the parsed clause AST and emits a Solidity contract fragment.
//
// Design choices (matching the architecture paper §6):
//   - Contract state is an enum; each clause function advances the state machine
//   - CEI pattern (checks → effects → interactions) enforced in every function
//   - ReentrancyGuard on all external-facing functions
//   - Oracle-dependent functions read price via IOracleModule, matching the
//     OracleModule already deployed in the Vault architecture
//   - Constants are derived from clause operands so the generated code is
//     auditable against the original CNL source
//
// The output is a standalone contract that can be compiled with:
//   npx hardhat compile
// after placing it in src/generated/.

function compile(ast, contractName = 'GeneratedContract') {
  const lines = [];

  lines.push('// SPDX-License-Identifier: MIT');
  lines.push('pragma solidity ^0.8.24;');
  lines.push('');
  lines.push('// Generated by defi-cnl-compiler — do not edit by hand.');
  lines.push(`// Source: ${ast.clauses.length} CNL clause(s)`);
  for (const c of ast.clauses) lines.push(`//   ${c.source}.`);
  lines.push('');

  // Imports
  lines.push('import {IERC20}        from "@openzeppelin/contracts/token/ERC20/IERC20.sol";');
  lines.push('import {SafeERC20}     from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";');
  lines.push('import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";');
  if (needsOracle(ast)) {
    lines.push('import {IOracleModule} from "../interfaces/IOracleModule.sol";');
  }
  lines.push('');

  lines.push(`/// @title  ${contractName}`);
  lines.push(`/// @notice Auto-generated from a CNL clause set (${ast.clauses.length} clauses).`);
  lines.push(`///         Each public function corresponds to one CNL clause.`);
  lines.push(`contract ${contractName} is ReentrancyGuard {`);
  lines.push('    using SafeERC20 for IERC20;');
  lines.push('');

  // State machine enum
  const states = deriveStates(ast);
  lines.push(`    // ── State machine derived from clause types ──`);
  lines.push(`    enum State { ${states.join(', ')} }`);
  lines.push('    State public state;');
  lines.push('');

  // Storage: token contracts
  if (ast.tokens.length > 0) {
    lines.push('    // ── Token contracts ──');
    for (const sym of ast.tokens) {
      lines.push(`    IERC20 public ${tokenVar(sym)};`);
    }
    lines.push('');
  }

  // Storage: oracle (if needed)
  if (needsOracle(ast)) {
    lines.push('    IOracleModule public oracleModule;');
    lines.push('');
  }

  // Storage: party addresses
  if (ast.parties.length > 0) {
    lines.push('    // ── Party addresses ──');
    for (const p of ast.parties) {
      lines.push(`    address public ${partyVar(p)};`);
    }
    lines.push('');
  }

  // Constants per clause
  const constants = buildConstants(ast);
  if (constants.length > 0) {
    lines.push('    // ── Clause constants ──');
    for (const c of constants) lines.push(`    ${c}`);
    lines.push('');
  }

  // Events
  const events = buildEvents(ast);
  if (events.length > 0) {
    lines.push('    // ── Events ──');
    for (const e of [...new Set(events)]) lines.push(`    ${e}`);
    lines.push('');
  }

  // Errors
  lines.push('    // ── Errors ──');
  lines.push('    error InvalidState(State current, State required);');
  lines.push('    error Unauthorised(address caller);');
  lines.push('    error ConditionNotMet(string reason);');
  lines.push('');

  // Constructor
  const ctorParams = buildCtorParams(ast);
  lines.push(`    constructor(`);
  lines.push(ctorParams.map(p => `        ${p}`).join(',\n'));
  lines.push('    ) {');
  for (const sym of ast.tokens) {
    lines.push(`        ${tokenVar(sym)} = IERC20(_${tokenVar(sym)});`);
  }
  if (needsOracle(ast)) {
    lines.push('        oracleModule = IOracleModule(_oracleModule);');
  }
  for (const p of ast.parties) {
    lines.push(`        ${partyVar(p)} = _${partyVar(p)};`);
  }
  lines.push('    }');
  lines.push('');

  // Clause functions
  lines.push('    // ════════════════════════════════════════════════════════════');
  lines.push('    //  Clause functions — one per CNL clause');
  lines.push('    // ════════════════════════════════════════════════════════════');
  lines.push('');

  for (let i = 0; i < ast.clauses.length; i++) {
    const fn = clauseFunction(ast.clauses[i], i + 1, ast);
    if (fn) { lines.push(fn); lines.push(''); }
  }

  lines.push('}');
  return lines.join('\n');
}

// ── State derivation ─────────────────────────────────────────────────────────

function deriveStates(ast) {
  const seen = new Set(['INITIAL']);
  for (const c of ast.clauses) {
    switch (c.type) {
      case 'CollateralLock':      seen.add('COLLATERAL_LOCKED');  break;
      case 'Obligation':          seen.add('OBLIGATION_ACTIVE');   break;
      case 'MarginCall':          seen.add('MARGIN_CALLED');       break;
      case 'Option':              seen.add('OPTION_ACTIVE');       break;
      case 'ConditionalTransfer': seen.add('CONDITION_MET');       break;
    }
  }
  seen.add('COMPLETED');
  return [...seen];
}

// ── Constant generation ──────────────────────────────────────────────────────

function buildConstants(ast) {
  const lines = [];
  for (let i = 0; i < ast.clauses.length; i++) {
    const c = ast.clauses[i];
    const n = i + 1;
    const comment = `// clause ${n}: ${c.source}.`;
    switch (c.type) {
      case 'CollateralLock':
        lines.push(`uint256 public constant AMOUNT_${n} = ${c.amount}e18; ${comment}`);
        break;
      case 'Transfer':
        lines.push(`uint256 public constant AMOUNT_${n} = ${c.amount}e18; ${comment}`);
        break;
      case 'Obligation':
        lines.push(`uint256 public constant AMOUNT_${n}   = ${c.amount}e18; ${comment}`);
        lines.push(`uint256 public constant DEADLINE_${n} = ${durationSecs(c.deadline)}; // ${c.deadline.amount} ${c.deadline.unit}`);
        break;
      case 'MarginCall':
        lines.push(`uint256 public constant MARGIN_TRIGGER_${n} = ${c.condition.price}e8; ${comment}`);
        lines.push(`uint256 public constant MARGIN_TOPUP_${n}   = ${c.topUpAmount}e18;`);
        lines.push(`uint256 public constant MARGIN_WINDOW_${n}  = ${durationSecs(c.deadline)}; // ${c.deadline.amount} ${c.deadline.unit}`);
        break;
      case 'ConditionalTransfer':
        lines.push(`uint256 public constant AMOUNT_${n}       = ${c.amount}e18; ${comment}`);
        lines.push(`uint256 public constant COND_PRICE_${n}   = ${c.condition.price}e8;`);
        break;
      case 'Option':
        lines.push(`uint256 public constant OPTION_GIVE_${n}    = ${c.giveAmount}e18; ${comment}`);
        lines.push(`uint256 public constant OPTION_RECEIVE_${n} = ${c.receiveAmount}e18;`);
        if (c.expiry) lines.push(`uint256 public constant OPTION_EXPIRY_${n} = ${durationSecs(c.expiry)}; // ${c.expiry.amount} ${c.expiry.unit}`);
        break;
    }
  }
  return lines;
}

// ── Event generation ─────────────────────────────────────────────────────────

function buildEvents(ast) {
  const events = [];
  for (const c of ast.clauses) {
    switch (c.type) {
      case 'CollateralLock':
        events.push('event CollateralLocked(address indexed party, uint256 amount, address token);'); break;
      case 'Transfer':
        events.push('event Transferred(address indexed from, address indexed to, uint256 amount, address token);'); break;
      case 'ConditionalTransfer':
        events.push('event ConditionalTransfer(address indexed from, address indexed to, uint256 amount, address token);'); break;
      case 'Obligation':
        events.push('event ObligationFulfilled(address indexed party, uint256 amount, address token);'); break;
      case 'MarginCall':
        events.push('event MarginCallTriggered(uint256 triggerPrice, uint256 deadline);'); break;
      case 'Option':
        events.push('event OptionExercised(address indexed holder, uint256 giveAmount, uint256 receiveAmount);'); break;
    }
  }
  return events;
}

// ── Constructor params ────────────────────────────────────────────────────────

function buildCtorParams(ast) {
  const params = [];
  for (const sym of ast.tokens)    params.push(`address _${tokenVar(sym)}`);
  if (needsOracle(ast))             params.push('address _oracleModule');
  for (const p   of ast.parties)   params.push(`address _${partyVar(p)}`);
  // Always need at least one param; if none derived, add a placeholder
  if (params.length === 0) params.push('address /* _placeholder */');
  return params;
}

// ── Clause function generation ────────────────────────────────────────────────

function clauseFunction(clause, n, ast) {
  const lines = [];
  lines.push(`    /// @notice Clause ${n}: ${clause.source}.`);

  switch (clause.type) {

    case 'CollateralLock': {
      const tv = tokenVar(clause.token);
      const pv = isKnownParty(clause.party) ? partyVar(clause.party) : null;
      lines.push(`    function lockCollateral_${n}() external nonReentrant {`);
      if (pv) lines.push(`        if (msg.sender != ${pv}) revert Unauthorised(msg.sender);`);
      lines.push(`        if (state != State.INITIAL) revert InvalidState(state, State.INITIAL);`);
      lines.push(`        // CEI: effects before interactions`);
      lines.push(`        state = State.COLLATERAL_LOCKED;`);
      lines.push(`        ${tv}.safeTransferFrom(msg.sender, address(this), AMOUNT_${n});`);
      lines.push(`        emit CollateralLocked(msg.sender, AMOUNT_${n}, address(${tv}));`);
      lines.push(`    }`);
      break;
    }

    case 'Transfer': {
      const tv  = tokenVar(clause.token);
      const isExternal = !isKnownParty(clause.from); // "vault" or other external source
      if (isExternal) {
        // External source already loaded the contract with tokens; recipient pulls them out.
        const toPv = partyVar(clause.to);
        lines.push(`    /// @dev Assumes tokens were pre-loaded into this contract by '${clause.from}'.`);
        lines.push(`    function receive_${n}() external nonReentrant {`);
        lines.push(`        if (msg.sender != ${toPv}) revert Unauthorised(msg.sender);`);
        lines.push(`        ${tv}.safeTransfer(${toPv}, AMOUNT_${n});`);
        lines.push(`        emit Transferred(address(this), ${toPv}, AMOUNT_${n}, address(${tv}));`);
        lines.push(`    }`);
      } else {
        const fromPv = partyVar(clause.from);
        const toPv   = isKnownParty(clause.to) ? partyVar(clause.to) : clause.to;
        lines.push(`    function transfer_${n}() external nonReentrant {`);
        lines.push(`        if (msg.sender != ${fromPv}) revert Unauthorised(msg.sender);`);
        lines.push(`        ${tv}.safeTransferFrom(${fromPv}, ${toPv}, AMOUNT_${n});`);
        lines.push(`        emit Transferred(${fromPv}, ${toPv}, AMOUNT_${n}, address(${tv}));`);
        lines.push(`    }`);
      }
      break;
    }

    case 'ConditionalTransfer': {
      const tv    = tokenVar(clause.token);
      const check = priceCheck(clause.condition, n);
      const toPv  = isKnownParty(clause.to) ? partyVar(clause.to) : `address(0) /* ${clause.to} */`;
      lines.push(`    function conditionalTransfer_${n}() external nonReentrant {`);
      lines.push(`        ${check}`);
      lines.push(`        if (state != State.COLLATERAL_LOCKED && state != State.OBLIGATION_ACTIVE) revert InvalidState(state, State.COLLATERAL_LOCKED);`);
      lines.push(`        state = State.CONDITION_MET;`);
      lines.push(`        ${tv}.safeTransfer(${toPv}, AMOUNT_${n});`);
      lines.push(`        emit ConditionalTransfer(address(this), ${toPv}, AMOUNT_${n}, address(${tv}));`);
      lines.push(`    }`);
      break;
    }

    case 'Obligation': {
      const tv = tokenVar(clause.token);
      const pv = partyVar(clause.party);
      const toPv = isKnownParty(clause.to) ? partyVar(clause.to) : `address(0) /* ${clause.to} */`;
      lines.push(`    function fulfillObligation_${n}() external nonReentrant {`);
      lines.push(`        if (msg.sender != ${pv}) revert Unauthorised(msg.sender);`);
      lines.push(`        if (state != State.OBLIGATION_ACTIVE) revert InvalidState(state, State.OBLIGATION_ACTIVE);`);
      lines.push(`        state = State.COMPLETED;`);
      lines.push(`        ${tv}.safeTransferFrom(${pv}, ${toPv}, AMOUNT_${n});`);
      lines.push(`        emit ObligationFulfilled(msg.sender, AMOUNT_${n}, address(${tv}));`);
      lines.push(`    }`);
      break;
    }

    case 'MarginCall': {
      const check = priceCheck(clause.condition, n);
      lines.push(`    function triggerMarginCall_${n}() external nonReentrant {`);
      lines.push(`        if (state != State.COLLATERAL_LOCKED) revert InvalidState(state, State.COLLATERAL_LOCKED);`);
      lines.push(`        ${check}`);
      lines.push(`        state = State.MARGIN_CALLED;`);
      lines.push(`        emit MarginCallTriggered(MARGIN_TRIGGER_${n}, block.timestamp + MARGIN_WINDOW_${n});`);
      lines.push(`    }`);
      break;
    }

    case 'Option': {
      const giveTV    = tokenVar(clause.giveToken);
      const receiveTV = tokenVar(clause.receiveToken);
      const holderPv  = partyVar(clause.holder);
      lines.push(`    function exerciseOption_${n}() external nonReentrant {`);
      lines.push(`        if (msg.sender != ${holderPv}) revert Unauthorised(msg.sender);`);
      lines.push(`        if (state != State.OPTION_ACTIVE) revert InvalidState(state, State.OPTION_ACTIVE);`);
      if (clause.expiry) {
        lines.push(`        // NOTE: add a startTime storage variable to enforce the expiry window on-chain.`);
        lines.push(`        // require(block.timestamp <= startTime + OPTION_EXPIRY_${n}, "option expired");`);
      }
      lines.push(`        state = State.COMPLETED;`);
      lines.push(`        ${giveTV}.safeTransferFrom(${holderPv}, address(this), OPTION_GIVE_${n});`);
      lines.push(`        ${receiveTV}.safeTransfer(${holderPv}, OPTION_RECEIVE_${n});`);
      lines.push(`        emit OptionExercised(${holderPv}, OPTION_GIVE_${n}, OPTION_RECEIVE_${n});`);
      lines.push(`    }`);
      break;
    }

    default:
      return null;
  }

  return lines.join('\n');
}

// ── Helper functions ─────────────────────────────────────────────────────────

function needsOracle(ast) {
  return ast.clauses.some(c =>
    c.condition && (c.condition.type === 'PriceBelow' || c.condition.type === 'PriceAbove')
  );
}

function tokenVar(sym) {
  return sym.toLowerCase() + 'Token';
}

function partyVar(party) {
  if (party.startsWith('Party ')) {
    return 'party' + party.slice(6).toUpperCase().replace(/\s+/g, '');
  }
  return party.toLowerCase().replace(/[^a-z0-9_]/g, '_');
}

function isKnownParty(name) {
  return name.startsWith('Party ');
}

function durationSecs(d) {
  const mul = { seconds: 1, minutes: 60, hours: 3600, days: 86400, weeks: 604800 };
  return parseInt(d.amount) * (mul[d.unit] || 86400);
}

function priceCheck(cond, clauseIndex) {
  if (cond.type === 'PriceBelow') {
    return `{ (uint256 _p,) = oracleModule.getPrice(); if (_p >= COND_PRICE_${clauseIndex} && _p >= MARGIN_TRIGGER_${clauseIndex}) revert ConditionNotMet("price not below trigger"); }`;
  }
  if (cond.type === 'PriceAbove') {
    return `{ (uint256 _p,) = oracleModule.getPrice(); if (_p <= COND_PRICE_${clauseIndex}) revert ConditionNotMet("price not above trigger"); }`;
  }
  return '// condition check (unrecognised type)';
}

module.exports = { compile };
